
version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb+srv://<user>:<pass>@cluster.mongodb.net/mydb
      STRIPE_SECRET_KEY: sk_test_123
