version: '3.8'
services:
  bot:
    build: .
    container_name: msio_bot
    volumes:
      - .:/app
    env_file:
      - .env
    command: bash run_bot.sh
  dashboard:
    image: streamlit
    ports:
      - '8501:8501'
    volumes:
      - .:/app
    working_dir: /app
    command: streamlit run dashboard/live_dashboard.py